# Generated by Django 4.2.1 on 2023-05-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlescope_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleScope', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
